version: '3'

services:
  web:
    image: nginx:alpine
    container_name: nginx_server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html  # Monta el directorio de tu proyecto en el contenedor
